dappx/urls.py
# dappx/urls.py
from django.conf.urls import url
from dappx import views
from django.urls import include, path

# SET THE NAMESPACE!
app_name = 'dappx'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    path('user_login/',views.user_login,name='user_login'),
    path('OTPAuthentication/',views.OTPAuthentication,name='OTPAuthentication'),
    path('QRAuthentication/',views.QRAuthentication,name='QRAuthentication')
]

dprojx/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from dappx import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^dappx/',include('dappx.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    path('dappx/opt_validator/',views.otp_validator,name='otp_validator'),
    path('dappx/qr_code/',views.qr_code,name='qr_code')
]

dappx/models.py
#from typing_extensions import Required
from django.db import models
from django.contrib.auth.models import User

#Create Your Models Here

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)

    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

def __str__(self):
    return self.user.username

    

dappx/forms.py
# dappx/forms.py
from django import forms
from dappx.models import UserProfileInfo
from django.contrib.auth.models import User
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')
class UserProfileInfoForm(forms.ModelForm):
     class Meta():
         model = UserProfileInfo
         fields = ('portfolio_site','profile_pic')

dappx/views.py
from django.shortcuts import render
from dappx.forms import UserForm, UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User,auth
from django.shortcuts import render,redirect
from random import randint
from django.core.mail import send_mail,EmailMessage
from django.conf import settings
from django.contrib import messages
from django.views.decorators.cache import cache_control
import qrcode

location = "/Users/sahilsharma/Downloads/djangoy/"
def index(request):
    return render(request,'dappx/index.html')

@login_required
def special(request):
    return HttpResponse("You are logged in !")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request,'dappx/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            user1 = User.objects.get(username=username)
            user_email = user.email
            if 'loginbtn' in request.POST and user.is_active:
                otp = randint(100000, 999999)
                print(otp)
                subject = "Login with OTP"
                sender = settings.EMAIL_HOST_USER
                message = "Hi,"+ str(user1)+" this is your OTP for logging into our system : " + str(otp) 
                val = send_mail(subject, message, sender, [user_email])
                if val:
                    request.session['username']=username
                    request.session['password']=password
                    request.session['otp']=otp
                    return HttpResponseRedirect(reverse(otp_validator))
                    
                else:
                    return HttpResponse("Your account was inactive.")
            elif 'loginbtn2' in request.POST:
                otp2 = randint(100000, 999999)
                qr = qrcode.QRCode(version=1,error_correction=qrcode.constants.ERROR_CORRECT_H,box_size=5,border=5)
                qr.add_data(username + ' ' + password + ' ' + str(otp2))
                qr.make(fit=True)
                img = qr.make_image(fill_color='black', back_color='white')
                img.save(location+'qrcode_'+str(user.username) +'.png')
                print('QR Code generated!!')
                
                email_sender = settings.EMAIL_HOST_USER
                subject = "Login with QR"
                message = "Hi,"+ str(user1)+", the QR for logging into our system is attached. Please login within 5 minutes."
                mail = EmailMessage(subject,message,email_sender,[user_email])
                mail.attach_file(location+'qrcode_'+str(username)+'.png')
                val = mail.send()
                if val:
                    print('Email was sent successfully')
                    request.session['username']=username
                    request.session['password']=password
                    request.session['otp2']=otp2
                    return HttpResponseRedirect(reverse(qr_code))
                    #return render(request, 'dappx/qr_code.html')
                else:
                    print('Email was not sent successfully')
                    #return redirect('../login')
        else:
            #print("Someone tried to login and failed.")
            #print("They used username: {} and password: {}".format(username,password))
            messages.error(request, 'Invalid Login.')
            return render(request, 'dappx/login.html')
            #return HttpResponse("Invalid login details given")
    else:
        return render(request, 'dappx/login.html', {})

def otp_validator(request):
    return render(request,'dappx/opt_validator.html')

def qr_code(request):
    return render(request,'dappx/qrcode.html')

def OTPAuthentication(request):
    if request.method == 'POST' and (request.session['username'] and request.session['password'] and request.session['otp']):
        OTP2 = request.POST['OTP']
        username = request.session['username']
        password = request.session['password']
        otp = request.session['otp']
        if (str(otp) == str(OTP2)):
            user=auth.authenticate(request,username=username,password=password)
            auth.login(request,user)
            return HttpResponseRedirect(reverse(index))
        else:
            messages.error(request, 'Invalid OTP.')
            return render(request, 'dappx/login.html')

def QRAuthentication(request):
    if request.method == 'POST' and (request.session['username'] and request.session['password'] and request.session['otp2']):
        #Take the session variable
        username = request.session['username']
        password = request.session['password']
        otp2 = request.session['otp2']
        #Take the variables from QR Code reader template
        credentials = request.POST['b']
        temp = credentials.split(" ")
        username2 = temp[0]
        password2 = temp[1]
        otp3 = temp[2]
        if (str(username)== str(username2) and str(password) ==str(password2) and str(otp2)== str(otp3)):
            user=auth.authenticate(request,username=username,password=password)
            auth.login(request,user)
            return HttpResponseRedirect(reverse(index))
        else:
           #print('Invalid credentials!!!')
            messages.error(request,'Invalid QR.')   
            return render(request,'dappx/login.html')
    elif request.method == 'GET' and (request.session['username'] and request.session['password']):
        return render(request,'dappx/qrcode.html')
       

templates/dappx/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'dappx/style.css' %}" />
    {% block head %}
    {% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">{# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'index' %}">E-Auth</a></li>
          <li><a class="navbar-brand" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-brand" href="{% url 'dappx:register' %}">Register</a></li>     
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a class="navbar-brand" href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-brand" href="{% url 'dappx:user_login' %}">Login</a></li>
          {% endif %}</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

templates/dappx/index.html
{% extends "dappx/base.html" %}
{% block body_block %}
<div class="form">
  <div class="jumbotron" style="background-image: url(https://github.com/sdas-ghub98/E_Authentication_System/blob/master/Media/img1.jpg); background-size: 10%;"> 
    <h1>Welcome to the E-AUTH !</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
    {% else %}
        <h2>Register or Login if you'd like to</h2>
    {% endif %}
  </div>
</div>

{% endblock %}

templates/dappx/login.html
{% extends 'dappx/base.html' %}
{% block body_block %}
  
  <div class="form">
    <div class="jumbotron"> 
      <h2>Login here :</h2><form class="login.form" method="post" action="{% url 'dappx:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username"><label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
          <input type="submit" name="loginbtn" value="Login with OTP">
          <input type="submit" name="loginbtn2" value="Login with QR"></form></div>
          
  </div>
  <div>
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
      </button>
      <strong>{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error{% else %}{{ message.tags|title }}{% endif %}!
      <h3></strong> {{ message }} </h3>
    </div>
    <!--<h3> {{message}} </h3> -->
    {% endfor %}
    {% endif %}
  </div>
<script>
    document.getElementById('LoginForm').onkeypress = function(e)
    {
        var key = e.charCode || e.keyCode || 0;
        if(key == 13)
        {
            e.preventDefault();
        }
    }
</script>
{% endblock %}

templates/dappx/opt_validator.html
{% extends 'dappx/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h2>OTP :</h2>
          {# A more "HTML" way of creating the login form#}
          <form method="post" action="{% url 'dappx:OTPAuthentication' %}">{% csrf_token %}
          <label for="OTP1"></label>
          <input type="text" name="OTP" placeholder="enter OTP">
          <input type="submit" name="OTPbtn" value="Submit">
          </form></div>
  </div>
{% endblock %}

templates/dappx/qrcode.html
{#% extends 'dappx/base.html' %#}
{% load static %}
{% block head %}
      <meta name="description" content="QR Code scanner" />
      <meta name="language" content="English" />
      <meta http-equiv="Content-type" content="text/html;charset=UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Login with QR</title>
    
    <style type="text/css">
    body{
        width:100%;
        text-align:center;
    }
    img{
        border:0;
    }
    #main{
        margin: 15px auto;
        background:white;
        overflow: auto;
        width: 100%;
    }
    #header{
        background:white;
        margin-bottom:15px;
    }
    #mainbody{
        background: white;
        width:100%;
        display:none;
    }
    #footer{
        background:white;
    }
    #v{
        width:320px;
        height:240px;
    }
    #qr-canvas{
        display:none;
    }
    #qrfile{
        width:320px;
        height:240px;
    }
    #mp1{
        text-align:center;
        font-size:35px;
    }
    #imghelp{
        position:relative;
        left:0px;
        top:-160px;
        z-index:100;
        font:18px arial,sans-serif;
        background:#f0f0f0;
        margin-left:35px;
        margin-right:35px;
        padding-top:10px;
        padding-bottom:10px;
        border-radius:20px;
    }
    .selector{
        margin:0;
        padding:0;
        cursor:pointer;
        margin-bottom:-5px;
    }
    #outdiv
    {
        width:320px;
        height:240px;
        border: solid;
        border-width: 3px 3px 3px 3px;
    }
    #result{
        border: solid;
        border-width: 1px 1px 1px 1px;
        padding:20px;
        width:70%;
    }
    
    ul{
        margin-bottom:0;
        margin-right:40px;
    }
    li{
        display:inline;
        padding-right: 0.5em;
        padding-left: 0.5em;
        font-weight: bold;
        border-right: 1px solid #333333;
    }
    li a{
        text-decoration: none;
        color: black;
    }
    
    #footer a{
        color: black;
    }
    .tsel{
        padding:0;
    }
    
    </style>
    
    <script type="text/javascript" src="{% static 'dappx/llqrcode.js' %}"></script>
    <script type="text/javascript" src="{% static 'dappx/plusone.js' %}"></script>
    <script type="text/javascript" src="{% static 'dappx/webqr.js'%}"></script>
    
    <script type="text/javascript">
    
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-24451557-1']);
      _gaq.push(['_trackPageview']);
    
      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    
    </script>
    
{% endblock %}
{% block body %}
    <div id="main">
    <div id="credentials" style="display: none;"></div>
    <div id="header">
    <div style="position:relative;top:+20px;left:0px;"><g:plusone size="medium"></g:plusone></div>
    <p id="mp1">
    Scan the QR mailed to your registered email ID
    </p>
    </div>
    <div id="mainbody">
    <table class="tsel" border="0" width="100%">
    <tr>
    <td valign="top" align="center" width="50%">
    <table class="tsel" border="0">
    <tr>
    <td><img class="selector" id="webcamimg" src="vid.png" onclick="setwebcam()" align="left" /></td>
    <!-- <td><img class="selector" id="qrimg" src="cam.png" onclick="setimg()" align="right"/></td></tr> -->
    <tr><td colspan="2" align="center">
    <div id="outdiv">
    </div></td></tr>
    </table>
    </td>
    </tr>
    <tr><td colspan="3" align="center">
    <div id="result" style="display: none;"></div>
    </td></tr>
    <tr>
        <td colspan="3" align="center">
            <form action="{% url 'dappx:QRAuthentication' %}" method="POST">
                {% csrf_token %}
                <input type="text" id="b" name="b" style="display: none;"/>
                <button type="submit">Submit QR Data</button>        
            </form>
        </td>
    </tr>
    </table>
    </div>&nbsp;
    </div>
    <canvas id="qr-canvas" width="800" height="600"></canvas>
    <script type="text/javascript">load();</script>
{% endblock%}

templates/dappx/registration.html
{% extends "dappx/base.html" %}
{% load static %}{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h2>Register Here</h2>
        <h3>Just fill out the form.</h3><form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}